catalog:
  iceberg_catalog:
    type: sql,
    uri: postgresql+psycopg2://iceberg:icebergpasswordpostgres_catalog:5432/iceberg_catalog,
    warehouse: s3://iceberg-warehouse/,
    s3_endpoint: http://minio:9000,
    s3_access_key_id: admin,
    s3_secret_access_key: password,
    s3_path_style_access: true