
# services:

#   controller:
#     image: 'trinodb/trino:475'
#     hostname: trino
#     volumes:
#       - ./etc/catalog:/etc/trino/catalog
#     ports:
#       - '8080:8080'
#     depends_on:
#       metastore:
#         condition: service_healthy
#       object-store:
#         condition: service_healthy

#   object-store:
#     image: minio/minio:RELEASE.2025-04-22T22-12-26Z
#     environment:
#       - MINIO_ROOT_USER=minio-user
#       - MINIO_ROOT_PASSWORD=minio-password
#     ports:
#       - 9001:9001
#       - 9000:9000
#     command: ["server", "/data", "--console-address", ":9001"]
#     healthcheck:
#       test: ["CMD-SHELL", "mc alias set minio http://localhost:9000 $${MINIO_ROOT_USER} $${MINIO_ROOT_PASSWORD} && mc mb minio/warehouse && mc anonymous set public minio/warehouse"]
#       interval: 2s
#       timeout: 2s
#       retries: 5

#   metastore:
#     image: postgres:alpine3.19
#     ports:
#       - 5432:5432
#     volumes:
#       - ./iceberg-setup.sql:/docker-entrypoint-initdb.d/iceberg-setup.sql
#     environment:
#       - POSTGRES_USER=postgres-user
#       - POSTGRES_PASSWORD=postgres-password
#       - POSTGRES_DB=iceberg
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres-user -d iceberg"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# # Flink Job Manager
#   flink-jobmanager:
#     image: flink-iceberg:latest
#     ports:
#       - "8081:8081"
#     command: jobmanager
#     networks:
#       iceberg-nessie-flink-net:
#     environment:
#       - |
#         FLINK_PROPERTIES=
#         jobmanager.rpc.address: flink-jobmanager
#       - AWS_ACCESS_KEY_ID=minio-user
#       - AWS_SECRET_ACCESS_KEY=minio-password
#       - AWS_REGION=us-east-1
#       - AWS_DEFAULT_REGION=us-east-1
#       - S3_ENDPOINT=http://minio.storage:9000
#       - S3_PATH_STYLE_ACCESS=true
#   # Flink Task Manager
#   flink-taskmanager:
#     image: alexmerced/flink-iceberg:latest
#     depends_on:
#       - flink-jobmanager
#     command: taskmanager
#     networks:
#       iceberg-nessie-flink-net:
#     scale: 1
#     environment:
#       - |
#         FLINK_PROPERTIES=
#         jobmanager.rpc.address: flink-jobmanager
#         taskmanager.numberOfTaskSlots: 2
#       - AWS_ACCESS_KEY_ID=admin
#       - AWS_SECRET_ACCESS_KEY=password
#       - AWS_REGION=us-east-1
#       - AWS_DEFAULT_REGION=us-east-1
#       - S3_ENDPOINT=http://minio.storage:9000
#       - S3_PATH_STYLE_ACCESS=true
# networks:
#   iceberg-nessie-flink-net:
